#define MQTT_CUSTOMER "viktak"
#define MQTT_PROJECT  "spiti"

#define HARDWARE_ID "ESP-12E-12F BB"
#define HARDWARE_VERSION "1.0"
#define SOFTWARE_ID "NeoPixel Clock"
#define FIRMWARE_VERSION "1.0"

#define JSON_SETTINGS_SIZE (JSON_OBJECT_SIZE(10) + 200)
#define JSON_MQTT_COMMAND_SIZE 300

#define CONNECTION_STATUS_LED_GPIO 0

#define DEFAULT_TEMPERATURE_REFRESH_INTERVAL 120
#define DEFAULT_HEARTBEAT_INTERVAL 300
